app/galamsey_portal/urls.py
from django.urls import path, include
from .views import *
from . import views_api as api_views
from root_app.views import reportsView, mapsView, contactView, articlesView,articleView, singleMapView

app_name = 'galamseyPortal'

########## API V1 URLS ##########
api_urlpatterns = [
    path('footprint', api_views.loadFootprint, name = 'api_load_galamsey_footprint'),

    # Analysis
    path('compute-analysis', api_views.analysisView, name = 'api_compute_analysis'),
    path('compute-stats', api_views.loadStatistics, name = 'api_load_statistics'),

    path('regions', api_views.getPilotRegions, name='api_get_regions'),
    path('districts', api_views.getPilotDistricts, name='api_get_districts'),
    path('protected-area', api_views.getPilotProtectedArea, name='api_get_protected_area'),

    # Additional Layers
    path('lulc-watershed', api_views.loadWaterShed, name='api_load_lulc_watershed'),
]

urlpatterns = [
    path("", mapView, name="galamsey_map_view"),
    path("custom-map", customMapView, name="galamsey_map"),
    path("data-request", dataRequestView, name="data_request"),
    path('footprint', loadFootprint, name='load_galamsey_footprint'),

    # Analysis 
    path('compute-analysis', analysisView, name='compute_analysis'),
    path('compute-stats', loadStatistics, name='load_statistics'),

    path('regions', getPilotRegions, name='get_regions'),
    path('districts', getPilotDistricts, name='get_districts'),
    path('protected-area', getPilotProtectedArea, name='get_protected_area'),

    # Reference Data
    path('deforestation-monitor', loadDeforestationData, name='load_deforestation_data'),
    
    # Planet Reference Data
    path('planet-basemap', loadPlanetData, name='load_planet_basemap'),

    # Additional Layers
    path('lulc-watershed', loadWaterShed, name='load_lulc_watershed'),

    # Reports
    path("reports", reportsView, name="galamsey_reports"),
    path("maps", mapsView, name="galamsey_maps"),
    path("map", singleMapView, name="galamsey_map_details"),
    path("articles", articlesView, name="galamsey_articels"),
    path("article", articleView, name="galamsey_articel"),
    path("contact", contactView, name="galamsey_contact"),

    # Dashboard URLS
    path('load-dashboard-protected-area', loadDashboardProtectedArea, name='load_dashboard_protected_area'),
    path('load-dashboard-districts', loadDashboardDistrictSummary, name='load_dashboard_districts'),

    # API URLS
    path('api/v1/', include(api_urlpatterns)),

]

app/home/urls.py
from django.urls import path
from .views import *

app_name = 'home'

urlpatterns = [
    path('', homeView, name="home_view"),
    path('service', serviceView, name="about_service_view"),
]

app/root_app/urls.py
from django.urls import path, include
from .views import *

app_name = 'rootApp'

urlpatterns = [

    path('region', RegionView.as_view(), name='region'),
    
    # path('get-districts', getDistricts, name='get_districts'),

    # path('district', DistrictView.as_view(), name='district'),

]

app/servir-portals/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from rest_framework import permissions
from drf_yasg.views import get_schema_view
from drf_yasg import openapi

...

schema_view = get_schema_view(
   openapi.Info(
      title="Galamsey Api",
      default_version='v1',
      description="API documentation for Geospatial data",
      contact=openapi.Contact(email="cersgis@gmail.com"),
   ),
   public=True,
   permission_classes=(permissions.AllowAny,),
)

admin.site.site_header = "servir-portals ADMIN"
admin.site.site_title = "servir-portals ADMIN"
admin.site.index_title = "servir-portals"


urlpatterns = [
    # path('admin/backups/', include('dbbackup_ui.urls')),
    path('admin/', admin.site.urls),
    path('api-documentation/', schema_view.with_ui('swagger', cache_timeout=0), name='schema-swagger-ui'),
    # path('redoc/', schema_view.with_ui('redoc', cache_timeout=0), name='schema-redoc'),
    path('', include('home.urls')),
    path('mining-portal/', include('galamsey_portal.urls')),
    path('charcoal-portal/', include('charcoal_portal.urls')),
    path('landscape-gh/', include('landscape_gh.urls')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app/root_app/models.py
from django.db import models

# Create your models here.


class Report(models.Model):
    SERVICES = [
    ('GALAMSEY', 'Galamsey Service'),
    ('CHARCOAL', 'Charcoal Service'),
    ]
        
    title = models.CharField(max_length=250, unique=True)
    service = models.CharField(max_length=20, choices=SERVICES, default='GALAMSEY')
    image = models.ImageField(upload_to='image/', blank=True, null=True)
    document = models.FileField(upload_to="reports")
    description = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)

app/root_app/views.py
from django.shortcuts import render
from galamsey_portal.models import Partner
from .models import *
# Create your views here.

def reportsView(request):
    path = request.path

    id = request.GET.get('id', None)
    toHTML  ={}

    # GET SINGLE REPORT
    # check if id is empty
    if id:
        toHTML["report"] = Report.objects.get(id=id)
        toHTML["reports"] = Report.objects.order_by("-created_at")[:5]
        return render(request, 'root_app/pages/report-details.html', toHTML)

    #------------- GET ALL -----------
    else:
        if "mining-portal" in path:
            report_data = Report.objects.filter(service='GALAMSEY').order_by('id')
        elif "charcoal" in path:
            report_data = Report.objects.filter(service='CHARCOAL').order_by('id')
        else:
            report_data = Report.objects.all().order_by('id')

        toHTML['reports'] = report_data

        return render(request, 'root_app/pages/reports.html', toHTML)
 
 

def mapsView(request):

    return render(request, 'root_app/pages/maps.html')

def singleMapView(request):

    return render(request, 'root_app/pages/map-details.html')

def articlesView(request):

    return render(request, 'root_app/pages/articles.html')

def articleView(request):

    return render(request, 'root_app/pages/article-details.html')

def contactView(request):

    return render(request, 'root_app/pages/contact.html')

app/root_app/templates/root_app/pages/article-details.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Document</title>
</head>
<body>
  
</body>
</html>

app/root_app/templates/root_app/pages/articles.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Document</title>
</head>
<body>
  <h1> Articles/ Blogs</h1>
</body>
</html>

app/root_app/templates/root_app/pages/contact.html
{% extends 'root_app/base-1.html' %}
{% load static %}


{% block title %}SSM Portal- Reports{% endblock %}
{% block css %}

{% endblock %}

{% block body %}


        <!-- Spinner Start -->
        <!-- <div id="spinner" class="show w-100 vh-100 bg-white position-fixed translate-middle top-50 start-50  d-flex align-items-center justify-content-center">
            <div class="spinner-grow text-primary" role="status"></div>
        </div> -->
        <!-- Spinner End -->


        <!-- Contact Start -->
        <div class="container-fluid contact py-5">
            <div class="container py-5">
                <div class="p-5 bg-light rounded">
                    <div class="row g-4">
               
                        <div class="col-lg-5 bg-info rounded">
                            <div class="">
                                <div class="mx-auto" style="max-width: 700px;">
                                    <h2 class="text-primary">Get in touch</h2>
                                    <p class="mb-4">The contact form is currently inactive.</p>
                                </div>
                            </div>
                            <div class="d-flex px-4 py-2 rounded mb-4 bg-white">
                                <i class="fas fa-map-marker-alt fa-2x text-primary me-4"></i>
                                <div>
                                    <h4>Address</h4>
                                    <p class="mb-2">PMB L17, Annie Jiagge St, University of Ghana - Legon -Accra.</p>
                                </div>
                            </div>
                            <div class="d-flex px-4 py-2 rounded mb-4 bg-white">
                                <i class="fas fa-envelope fa-2x text-primary me-4"></i>
                                <div>
                                    <h4>Mail Us</h4>
                                    <a href="mailto:cersgis@ug.edu.gh" class="mb-2">cersgis@ug.edu.gh</a>
                                </div>
                            </div>
                            <div class="d-flex px-4 py-2 rounded bg-white">
                                <i class="fa fa-phone-alt fa-2x text-primary me-4"></i>
                                <div>
                                    <h4>Telephone</h4>
                                    <p class="mb-2">(+233) 0303974211</p>
                                </div>
                            </div>
                        </div>
                        <div class="col-lg-7">
                            <form action="" class="">
                                <input type="text" class="w-100 form-control border-0 py-3 mb-4" placeholder="Your Name">
                                <input type="email" class="w-100 form-control border-0 py-3 mb-4" placeholder="Enter Your Email">
                                <textarea class="w-100 form-control border-0 mb-4" rows="7" cols="10" placeholder="Your Message"></textarea>
                                <button class="w-100 btn form-control border-secondary py-3 bg-white text-primary " type="submit">Submit</button>
                            </form>
                        </div>

                         <div class="col-lg-12">
                            <div class="h-100 rounded">
                                <iframe class="rounded w-100"  
                                style="height: 400px;" src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d5588.581083740963!2d-0.18549462372728925!3d5.651379132680553!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0xfdf9c86ae080cc1%3A0x60d7aa1d9e994be7!2sCentre%20for%20Remote%20Sensing%20and%20Geographic%20Information%20Services!5e1!3m2!1sen!2sgh!4v1739192111247!5m2!1sen!2sgh" 
                                allowfullscreen=""  loading="lazy" referrerpolicy="no-referrer-when-downgrade"></iframe>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- Contact End -->
        
        
        
        
        
        
        <!-- Contact -->
        <!-- <div class="container" data-aos="fade-up" data-aos-delay="100">

            <div class="row gy-4">
              <div class="col-lg-6 ">
                <div class="row gy-4">
    
                  <div class="col-lg-12">
                    <div class="info-item d-flex flex-column justify-content-center align-items-center" data-aos="fade-up" data-aos-delay="200">
                      <i class="bi bi-geo-alt"></i>
                      <h3>Address</h3>
                      <p>A108 Adam Street, New York, NY 535022</p>
                    </div>
                  </div>
    
                  <div class="col-md-6">
                    <div class="info-item d-flex flex-column justify-content-center align-items-center" data-aos="fade-up" data-aos-delay="300">
                      <i class="bi bi-telephone"></i>
                      <h3>Call Us</h3>
                      <p>+1 5589 55488 55</p>
                    </div>
                  </div>
    
                  <div class="col-md-6">
                    <div class="info-item d-flex flex-column justify-content-center align-items-center" data-aos="fade-up" data-aos-delay="400">
                      <i class="bi bi-envelope"></i>
                      <h3>Email Us</h3>
                      <p>info@example.com</p>
                    </div>
                  </div>

                </div>
              </div>
    
              <div class="col-lg-6">
                <form action="forms/contact.php" method="post" class="php-email-form" data-aos="fade-up" data-aos-delay="500">
                  <div class="row gy-4">
    
                    <div class="col-md-6">
                      <input type="text" name="name" class="form-control" placeholder="Your Name" required="">
                    </div>
    
                    <div class="col-md-6 ">
                      <input type="email" class="form-control" name="email" placeholder="Your Email" required="">
                    </div>
    
                    <div class="col-md-12">
                      <input type="text" class="form-control" name="subject" placeholder="Subject" required="">
                    </div>
    
                    <div class="col-md-12">
                      <textarea class="form-control" name="message" rows="4" placeholder="Message" required=""></textarea>
                    </div>
    
                    <div class="col-md-12 text-center">
                      <div class="loading">Loading</div>
                      <div class="error-message"></div>
                      <div class="sent-message">Your message has been sent. Thank you!</div>
    
                      <button type="submit">Send Message</button>
                    </div>
    
                  </div>
                </form>
              </div> -->
              <!-- End Contact Form -->
    



{% endblock %}


{% block js %}
{% endblock %}

app/root_app/templates/root_app/pages/map-details.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Document</title>
</head>
<body>
  <h1> Map details</h1>
</body>
</html>

app/root_app/templates/root_app/pages/maps.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>Maps</h1>
</body>
</html>

app/root_app/templates/root_app/pages/report-details.html
{% extends 'root_app/base-1.html' %}
{% load static %}

{% block title %}SSM Portal- Reports{% endblock %}

{% block css %}
  <!-- Main CSS File -->
  <link href="{% static 'root_app/assets/styles/article.css' %}" rel="stylesheet">
{% endblock %}
  
{% block body %}
    <!-- Page Title -->
    <!-- <div class="page-title dark-background" data-aos="fade" style="background-image: url({% static 'root_app/assets/article/img/page-title-bg.webp' %});"> -->
    <div class="page-title dark-background" data-aos="fade" style="background-image: url({% static 'galamsey_portal/assets/images/report-details.webp' %});">
      <div class="container position-relative">
        <h1>Report Details</h1>
        <p>Unlock actionable insights with our comprehensive report details—explore dynamic visualizations, and trends that empower smarter decisions.</p>
        <nav class="breadcrumbs">
          <ol>
            <li><a href="index.html">Home</a></li>
            <li class="current">Report Details</li>
          </ol>
        </nav>
      </div>
    </div><!-- End Page Title -->

    <div class="container">
      <div class="row">

        <div class="col-lg-8">

          <!-- Blog Details Section -->
          <section id="blog-details" class="blog-details section">
            <div class="container">

              <article class="article">

                <div class="post-img">
                  {% if report.image %}
                <img class="" src="{{report.image.url}}">
              {% else %}
                <img class="" src="/static/assets/landing/images/thumbnail.jpg" alt="{{ report.title}}"/>
              {% endif %}
                </div>

                <h2 class="title">{{report.title |title}}</h2>

                <div class="meta-top">
                  <ul>
                    <li class="d-flex align-items-center"><i class="bi bi-person"></i> <a href="blog-details.html">CERSGIS</a></li>
                    <li class="d-flex align-items-center"><i class="bi bi-clock"></i> <a href="blog-details.html"><time datetime="2020-01-01">{{report.created_at | date:"M j, Y"}}</time></a></li>
                  </ul>
                </div><!-- End meta top -->

                <div class="content">
                  <p>
                    {{report.description }} 
                  </p>

                </div><!-- End post content -->

                <div class="meta-bottom">
                  <i class="bi bi-tags"></i>
                  <ul class="tags">
                    <li><a href="#">Galamsey</a></li>
                    <li><a href="#">Mining</a></li>
                    <li><a href="#">Forest degradation</a></li>
                  </ul>
                </div><!-- End meta bottom -->

              </article>

            </div>
          </section><!-- /Blog Details Section -->


        </div>

        <div class="col-lg-4 sidebar">

          <div class="widgets-container">

            <!-- Search Widget -->
            <div class="search-widget widget-item">

              <h3 class="widget-title">Search</h3>
              <form action="">
                <input type="text">
                <button type="submit" title="Search"><i class="bi bi-search"></i></button>
              </form>

            </div><!--/Search Widget -->

            <!-- Categories Widget -->
            <div class="categories-widget widget-item">

              <h3 class="widget-title">Categories</h3>
              <ul class="mt-3">
                <li><a href="#">General <span>(3)</span></a></li>
                <!-- <li><a href="#">Lifestyle <span>(12)</span></a></li>
                <li><a href="#">Travel <span>(5)</span></a></li>
                <li><a href="#">Design <span>(22)</span></a></li>
                <li><a href="#">Creative <span>(8)</span></a></li>
                <li><a href="#">Educaion <span>(14)</span></a></li> -->
              </ul>

            </div><!--/Categories Widget -->

            <!-- Recent Posts Widget -->
            <div class="recent-posts-widget widget-item">

              <h3 class="widget-title">Recent Posts</h3>

              {% for report in reports %}
              <div class="post-item">
                {% if report.image %}
                <img class="flex-shrink-0" src="{{report.image.url}}">
              {% else %}
                <img class="flex-shrink-0" src="/static/assets/landing/images/thumbnail.jpg" alt="{{ report.title}}"/>
              {% endif %}
                <div>
                  <h4><a href="blog-details.html">{{report.title |title |truncatechars:47}}</a></h4>
                  <time datetime="2020-01-01">{{report.created_at | date:"M j, Y"}}</time>
                </div>
              </div>
              {% endfor %}
              <!-- End recent post item-->
            </div>
            <!--/Recent Posts Widget -->

          </div>

        </div>

      </div>
    </div>



  <!-- Scroll Top -->
  <a href="#" id="scroll-top" class="scroll-top d-flex align-items-center justify-content-center"><i class="bi bi-arrow-up-short"></i></a>

  <!-- Preloader -->
  <div id="preloader"></div>

  <!-- Vendor JS Files -->


  {% endblock %}


{% block js %}
  <!-- Main JS File -->
  <script src="{% static 'root_app/assets/js/article.js' %}"></script>


{% endblock %}

app/root_app/templates/root_app/pages/reports.html
{% extends 'root_app/base-1.html' %}
{% load static %}

{% block title %}SSM Portal- Reports{% endblock %}

{% block css %}
  <!-- Main CSS File -->
  <link href="{% static 'root_app/assets/styles/article.css' %}" rel="stylesheet">
{% endblock %}
  
{% block body %}

    <!-- Page Title -->
    <div class="page-title dark-background" data-aos="fade" style="background-image: url({% static 'assets/landing/images/slider-bg.jpg' %});">
      <div class="container position-relative">
        <h1>Reports</h1>
        <p>Get detailed reports on mining activities. Track trends, analyze data, and stay informed to help protect our environment.</p>
        <nav class="breadcrumbs">
          <ol>
            <li><a href="index.html">Home</a></li>
            <li class="current">Reports</li>
          </ol>
        </nav>
      </div>
    </div>
    <!-- End Page Title -->


 <!-- Blog Posts Section -->
 <section id="report-posts" class="report-posts section">

    <div class="container">
      <div class="row gy-4">

        {% for report in reports %}
        <div class="col-lg-4">
          <article class="position-relative report-item h-100">

            <div class="post-img position-relative overflow-hidden">

              {% if report.image %}
                <img class="" src="{{report.image.url}}">
              {% else %}
                <img class="" src="/static/assets/landing/images/thumbnail.jpg" alt="{{ report.title}}"/>
              {% endif %}
              <span class="post-date">{{report.created_at | date:"F j"}}</span>
            </div>

            <div class="post-content d-flex flex-column">

              <h3 class="post-title">{{report.title |title}}</h3>

              <p>
                {{report.description |truncatechars:135}}
              </p>

              <hr>

              <a href="{% url 'galamseyPortal:galamsey_reports' %}?id={{report.id}}" class="readmore stretched-link"><span>Read More</span><i class="bi bi-arrow-right"></i></a>

            </div>

          </article>
        </div>
        {% endfor %}
        <!-- End post list item -->

      </div>
    </div>

  </section>
  <!-- /Blog Posts Section -->


    <!-- Blog Pagination Section -->
    <section id="blog-pagination" class="blog-pagination section">

      <div class="container">
        <div class="d-flex justify-content-center">
          <ul>
            <li><a href="#"><i class="bi bi-chevron-left"></i></a></li>
            <li><a href="#">1</a></li>
            <li><a href="#" class="active">2</a></li>
            <li><a href="#">3</a></li>
            <li><a href="#">4</a></li>
            <li>...</li>
            <li><a href="#">10</a></li>
            <li><a href="#"><i class="bi bi-chevron-right"></i></a></li>
          </ul>
        </div>
      </div>

    </section>
    <!-- /Blog Pagination Section -->


  <!-- Preloader -->
  <div id="preloader"></div>


  {% endblock %}


{% block js %}
  <!-- Main JS File -->
  <script src="{% static 'root_app/assets/js/article.js' %}"></script>


{% endblock %}