app/home/urls.py
from django.urls import path
from .views import *

app_name = 'home'

urlpatterns = [
    path('', homeView, name="home_view"),
    path('service', serviceView, name="about_service_view"),
]

app/servir-portals/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from rest_framework import permissions
from drf_yasg.views import get_schema_view
from drf_yasg import openapi

...

schema_view = get_schema_view(
   openapi.Info(
      title="Galamsey Api",
      default_version='v1',
      description="API documentation for Geospatial data",
      contact=openapi.Contact(email="cersgis@gmail.com"),
   ),
   public=True,
   permission_classes=(permissions.AllowAny,),
)

admin.site.site_header = "servir-portals ADMIN"
admin.site.site_title = "servir-portals ADMIN"
admin.site.index_title = "servir-portals"


urlpatterns = [
    # path('admin/backups/', include('dbbackup_ui.urls')),
    path('admin/', admin.site.urls),
    path('api-documentation/', schema_view.with_ui('swagger', cache_timeout=0), name='schema-swagger-ui'),
    # path('redoc/', schema_view.with_ui('redoc', cache_timeout=0), name='schema-redoc'),
    path('', include('home.urls')),
    path('mining-portal/', include('galamsey_portal.urls')),
    path('charcoal-portal/', include('charcoal_portal.urls')),
    path('landscape-gh/', include('landscape_gh.urls')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app/home/models.py
from django.db import models

# Create your models here.
class Service(models.Model):
    name = models.CharField(max_length=500, unique=True)
    details = models.CharField(max_length=1000, blank=True, null=True)
    image = models.ImageField(upload_to='service-image/', blank=True, null=True)
    url = models.URLField(unique=True)

class GlobalPartner(models.Model):
    name = models.CharField(max_length=500, unique=True)
    logo = models.ImageField(upload_to='logo/', blank=True, null=True)
    url = models.URLField(unique=True)

class RecipientEmail(models.Model):
    first_name = models.CharField(max_length=250, unique=True)
    last_name = models.CharField(max_length=250, unique=True)
    email = models.EmailField(unique=True, blank=True)
    receive_galamsey_email = models.BooleanField(default=False)
    receive_charcoal_email = models.BooleanField(default=False)

app/home/views.py
from django.shortcuts import render
from django.core.paginator import Paginator
from home.models import Service, GlobalPartner


# Create your views here.

def homeView(request):
    page = int(request.GET.get('page', 1))

    toHTML = {}

    paginator = Paginator(Service.objects.all().order_by('-id'), 8)
    toHTML['services'] = paginator.page(page)
    toHTML['globalPartners'] = GlobalPartner.objects.all().order_by('-id')
    return render(request, 'home/landing.html', toHTML)
    

def serviceView(request):
    id = request.GET.get('id', None)

    toHTML = {}
    print("here------------------")

    if id or id != None:
        service_data = Service.objects.get(id = id)
        toHTML['service'] = service_data
        return render(request, 'home/about.html', toHTML)
    

app/home/templates/home/about.html
{% extends 'home/base.html' %}
{% load static %}


{% block body %}

    <div id="about-service">
        {% if service %}
        <div class="top-box">
            <img class="top-img" src="/static/assets/landing/images/slider-bg.jpg" alt="">
            <div class="top-logo-div">
                <a href="{% url 'home:home_view' %}"><img class="top-logo" src="/static/assets/landing/images/s-wa1.png" /></a>
            </div>

        </div>

        <div class="service-container">
            <div class="row row-cols-md-2 row-cols-lg-2 row-cols-1 ">
                <div class="col d-flex flex-column justify-content-center align-items-center">
                    <div class="image-col">
                        {% if service.image %}
                        <img class="w-100 h-100 rounded" src="{{ service.image.url }}" />
                        {% else %}
                        <img class="w-100 h-100 rounded" src="/static/assets/landing/images/thumbnail.jpg" />
                        {% endif %}
                    </div>
                    <button class="btn btn-outline-primary m-auto mt-2 w-25" onclick="window.open('{{service.url}}',  '_blank')">Open App</button>
                </div>
                
                <div class="col">
                    <div class="px-5">
                        <h1 class="title">{{service.name}}</h1>
                        <p>{{service.details}}</p>
                    </div>
                </div>
                
            </div>
        </div>
        {% endif %}

    </div>
{% endblock %}

{% block js %}

{% endblock %}

app/home/templates/home/base.html
{% load static %}
<!DOCTYPE html>
<html>

<head>
    <!-- Basic -->
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <!-- Mobile Metas -->
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <!-- Site Metas -->
    <meta name="keywords" content="" />
    <meta name="description" content="" />
    <meta name="author" content="" />
    <!-- <link rel="shortcut icon" href="/static/assets/landing/images/favicon.png" type=""> -->
    <title>SERVIR :: West Africa</title>

    <!-- Favicon -->
    <link href="{% static 'assets/landing/images/partners/servir-favicon.png' %}" rel="icon">

    <!-- bootstrap core css -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <!-- <link rel="stylesheet" type="text/css" href="/static/assets/landing/css/bootstrap.css" /> -->

    <!-- font awesome style -->
    <link href="/static/assets/landing/css/font-awesome.min.css" rel="stylesheet" />
    <!-- Custom styles for this template -->
    <link href="/static/assets/landing/css/style.css" rel="stylesheet" />
    <!-- responsive style -->
    <link href="/static/assets/landing/css/responsive.css" rel="stylesheet" />

    <!-- Font awesome -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.2/css/all.min.css" integrity="sha512-SnH5WK+bZxgPHs44uWIX+LLJAJ9/2PkPKZ5QiAj6Ta86w+fsb2TkcmfRyVX3pBnMFcV7oQPJkl9QevSCWr3W6A==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <style type="text/css">
    .slideX {
        display: inline-flex;
        width: 12.6%;
        margin: 0.5%;
        height: 100px;
        padding: 20px;
    }


    .slideX>img { margin:1px auto; }

    .slide >img {
        width: 100%;
        height: auto;
    }
    </style>

    {% block css %}
    {% endblock %}

</head>

<body>

    <div class="body-container">
        {% block body %}
        {% endblock %}
    </div>

    <div class="cpy_">
        <!-- <p class="mx-auto">© {% now "Y" %} all rights reserved by <a style="color: #fff;" href="https://cersgis.org/" style="font-size: 13px;">CERSGIS</a> -->
        <p class="mx-auto">© {% now "Y" %} all rights reserved by SERVIR WEST AFRICA</p>
    </div>


   <!-- jQery -->
   <script src="/static/assets/landing/js/jquery-3.4.1.min.js"></script>
   <!-- popper js -->
   <script src="/static/assets/landing/js/popper.min.js"></script>
   <!-- bootstrap js -->
   <!-- <script src="/static/assets/landing/js/bootstrap.js"></script> -->
   <!-- custom js -->
   <script src="/static/assets/landing/js/custom.js"></script>

    {% block js %}
    {% endblock %}
</body>

</html>

app/home/templates/home/landing.html
{% extends 'home/base.html' %}
{% load static %}


{% block body %}
    <div id="landing_page">
    <div class="hero_area">
        <!-- slider section -->
        <section class="slider_section ">
            <div class="slider_bg_box">
                <img src="/static/assets/landing/images/slider-bg.jpg" alt="">
            </div>
            <div id="customCarousel1" class="carousel slide" data-ride="carousel">
                <div class="carousel-inner">
                    <div class="carousel-item active">
                        <div class="container-fluid">
                            <div class="row">
                                <div class="col-md-12 col-lg-12">
                                    <div class="detail-box" align="center">
                                       <img class="" src="/static/assets/landing/images/s-wa1.png" />
                                        <h1>
                                          Connecting Space to Village in West Africa 
                                        </h1>
                                        <p>
                                            SERVIR-West Africa is a geospatial data-for-development program <br> that responds to the needs of West African countries
                                        </p>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>

            </div>
        </section>
        <!-- end slider section -->
    </div>
    <!-- why section -->
    <section class="why_section layout_padding">
        <div class="container">
            <div class="heading_container heading_center">
                <h2>
                    Decision Support Services
                </h2>
                <div class="row">
                    <div class="col-md-10 offset-md-1">
                        <p>These user-tailored applications have been developed to address the information gap on climate-sensitive challenges such as disasters, agriculture, water management, ecosystem protection and land use.</p>
                    </div>
                </div>
            </div>
        </div>
    </section>

    <!-- end why section -->
    <!-- why section -->
    <section class="why_section layout_padding">
        <div class="container-lg">

            <div class="row row-cols-md-4">

                {% for service in services %}
                <div class="col">
                    <div class="mybox" onclick="window.location.href =`{% url 'home:about_service_view' %}?id={{ service.id }}`">
                        {% if service.image %}
                            <img class="w-100 h-100" src="{{ service.image.url }}" />
                        {% else %}
                            <img class="w-100 h-100" src="/static/assets/landing/images/thumbnail.jpg" />
                        {% endif %}
                        <div class="box-content d-flex justify-content-between align-items-center">
                            <h3 class="title">{{service.name | truncatechars:26}}</h3>
                            <a href="{{ service.url }}"  target="_blank" onclick="event.stopPropagation();"><i class="link-icon fa-solid fa-link"></i></a>
                        </div>
                        </a>
                    </div>
                </div>
                {% endfor %}
                
            </div>

            <div>
        {% if services.has_other_pages %}
        <ul class="pagination">
            {% if services.has_previous %}
            <li><a href="?{% if request.GET.sector %}sector={{request.GET.sector}}&{% endif %}page={{ services.previous_page_number }}" aria-label="Previous"><i class="fa-solid fa-left-long"></i></a></li>
            {% else %}
            <li class="disabled"><span>&laquo;</span></li>
            {% endif %}

            {% for i in services.paginator.page_range %}

            {% if services.number == i %}
            <li class="active"><a>{{ i }}</a></li>
            {% else %}
            <li><a href="{{request.path}}?{% if request.GET.sector %}sector={{request.GET.sector}}&{% endif %}page={{ i }}">{{ i }}</a></li>
            {% endif %}
            {% endfor %} 
            
            {% if services.has_next %}
            <li><a href="{{request.path}}?{% if request.GET.sector %}sector={{request.GET.sector}}&{% endif %}page={{ services.next_page_number }}" aria-label="Next"><i class="fa-solid fa-right-long"></i></a></li>
            {% else %}
            <li class="disabled"><span>&raquo;</span></li>
            {% endif %}
        </ul>
        {% endif %}
    </div>
        </div>
    </section>

    <!-- end why section -->
    <!-- why section -->
    <section class="why_section layout_padding">
        <div class="container mt-5">
            <div class="heading_container heading_center">
                <!-- <h2 style="font-weight: normal; font-size: 20px;"> -->
                <h2 >
                    Partners
                </h2>
            </div>
            <div class="row">
                <div class="col-md-12">
                    <div class="customer-logos slider">
                        {% for globalPartner in globalPartners %}
                        <div class="slideX" onclick="window.open('{{ globalPartner.url }}', '_blank')" >
                        {% if globalPartner.logo %}
                            <img src="{{ globalPartner.logo.url }}" alt="{{ globalPartner.name }}">
                        {% else %}
                            <img src="/static/assets/landing/images/thumbnail.jpg" alt="{{ globalPartner.name }}"/>
                        {% endif %}
                        </div>
                        {% endfor %}
                    </div>
                </div>
            </div>
        </div>
    </section>

</div>
{% endblock %}

{% block js %}
 
{% endblock %}