app/charcoal_portal/urls.py
from django.urls import path, include
from .views import *
from . import views_api as api_views


app_name = 'charcoalPortal'

########## API V1 URLS ##########
api_urlpatterns = [
    # Analysis
    path('compute-analysis', api_views.analysisView, name = 'api_compute_analysis'),
    path('compute-stats', api_views.loadStatistics, name = 'api_load_statistics'),

    path('regions', api_views.getCharcoalRegions, name='api_get_regions'),
    path('districts', api_views.getCharcoalDistricts, name='api_get_districts'),

    # Watershed
    path('load-watershed', api_views.loadWaterShed, name='api_load_watershed'),
]

urlpatterns = [
    path('', mapView, name="charcoal_map_view"),
    path("data-request", dataRequestView, name="data_request"),

    # Analysis
    path('compute-analysis', analysisView, name='compute_analysis'),
    path('compute-stats', loadStatistics, name='load_statistics'),

    path('regions', getCharcoalRegions, name='get_regions'),
    path('districts', getCharcoalDistricts, name='get_districts'),

    # Additional Layers
    path('lulc-watershed', loadWaterShed, name='load_lulc_watershed'),
    
    #Dashboard URLS
    path('load-dashboard-districts', loadDashboardDistrictSummary, name='load_dashboard_districts'),


    # API URLS
    path('api/v1/', include(api_urlpatterns)),

]

app/galamsey_portal/urls.py
from django.urls import path, include
from .views import *
from . import views_api as api_views
from root_app.views import reportsView, mapsView, contactView, articlesView,articleView, singleMapView

app_name = 'galamseyPortal'

########## API V1 URLS ##########
api_urlpatterns = [
    path('footprint', api_views.loadFootprint, name = 'api_load_galamsey_footprint'),

    # Analysis
    path('compute-analysis', api_views.analysisView, name = 'api_compute_analysis'),
    path('compute-stats', api_views.loadStatistics, name = 'api_load_statistics'),

    path('regions', api_views.getPilotRegions, name='api_get_regions'),
    path('districts', api_views.getPilotDistricts, name='api_get_districts'),
    path('protected-area', api_views.getPilotProtectedArea, name='api_get_protected_area'),

    # Additional Layers
    path('lulc-watershed', api_views.loadWaterShed, name='api_load_lulc_watershed'),
]

urlpatterns = [
    path("", mapView, name="galamsey_map_view"),
    path("custom-map", customMapView, name="galamsey_map"),
    path("data-request", dataRequestView, name="data_request"),
    path('footprint', loadFootprint, name='load_galamsey_footprint'),

    # Analysis 
    path('compute-analysis', analysisView, name='compute_analysis'),
    path('compute-stats', loadStatistics, name='load_statistics'),

    path('regions', getPilotRegions, name='get_regions'),
    path('districts', getPilotDistricts, name='get_districts'),
    path('protected-area', getPilotProtectedArea, name='get_protected_area'),

    # Reference Data
    path('deforestation-monitor', loadDeforestationData, name='load_deforestation_data'),
    
    # Planet Reference Data
    path('planet-basemap', loadPlanetData, name='load_planet_basemap'),

    # Additional Layers
    path('lulc-watershed', loadWaterShed, name='load_lulc_watershed'),

    # Reports
    path("reports", reportsView, name="galamsey_reports"),
    path("maps", mapsView, name="galamsey_maps"),
    path("map", singleMapView, name="galamsey_map_details"),
    path("articles", articlesView, name="galamsey_articels"),
    path("article", articleView, name="galamsey_articel"),
    path("contact", contactView, name="galamsey_contact"),

    # Dashboard URLS
    path('load-dashboard-protected-area', loadDashboardProtectedArea, name='load_dashboard_protected_area'),
    path('load-dashboard-districts', loadDashboardDistrictSummary, name='load_dashboard_districts'),

    # API URLS
    path('api/v1/', include(api_urlpatterns)),

]

app/home/urls.py
from django.urls import path
from .views import *

app_name = 'home'

urlpatterns = [
    path('', homeView, name="home_view"),
    path('service', serviceView, name="about_service_view"),
]

app/root_app/urls.py
from django.urls import path, include
from .views import *

app_name = 'rootApp'

urlpatterns = [

    path('region', RegionView.as_view(), name='region'),
    
    # path('get-districts', getDistricts, name='get_districts'),

    # path('district', DistrictView.as_view(), name='district'),

]

app/servir-portals/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from rest_framework import permissions
from drf_yasg.views import get_schema_view
from drf_yasg import openapi

...

schema_view = get_schema_view(
   openapi.Info(
      title="Galamsey Api",
      default_version='v1',
      description="API documentation for Geospatial data",
      contact=openapi.Contact(email="cersgis@gmail.com"),
   ),
   public=True,
   permission_classes=(permissions.AllowAny,),
)

admin.site.site_header = "servir-portals ADMIN"
admin.site.site_title = "servir-portals ADMIN"
admin.site.index_title = "servir-portals"


urlpatterns = [
    # path('admin/backups/', include('dbbackup_ui.urls')),
    path('admin/', admin.site.urls),
    path('api-documentation/', schema_view.with_ui('swagger', cache_timeout=0), name='schema-swagger-ui'),
    # path('redoc/', schema_view.with_ui('redoc', cache_timeout=0), name='schema-redoc'),
    path('', include('home.urls')),
    path('mining-portal/', include('galamsey_portal.urls')),
    path('charcoal-portal/', include('charcoal_portal.urls')),
    path('landscape-gh/', include('landscape_gh.urls')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app/root_app/models.py
from django.db import models

# Create your models here.


class Report(models.Model):
    SERVICES = [
    ('GALAMSEY', 'Galamsey Service'),
    ('CHARCOAL', 'Charcoal Service'),
    ]
        
    title = models.CharField(max_length=250, unique=True)
    service = models.CharField(max_length=20, choices=SERVICES, default='GALAMSEY')
    image = models.ImageField(upload_to='image/', blank=True, null=True)
    document = models.FileField(upload_to="reports")
    description = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)

app/root_app/views.py
from django.shortcuts import render
from galamsey_portal.models import Partner
from .models import *
# Create your views here.

def reportsView(request):
    path = request.path

    id = request.GET.get('id', None)
    toHTML  ={}

    # GET SINGLE REPORT
    # check if id is empty
    if id:
        toHTML["report"] = Report.objects.get(id=id)
        toHTML["reports"] = Report.objects.order_by("-created_at")[:5]
        return render(request, 'root_app/pages/report-details.html', toHTML)

    #------------- GET ALL -----------
    else:
        if "mining-portal" in path:
            report_data = Report.objects.filter(service='GALAMSEY').order_by('id')
        elif "charcoal" in path:
            report_data = Report.objects.filter(service='CHARCOAL').order_by('id')
        else:
            report_data = Report.objects.all().order_by('id')

        toHTML['reports'] = report_data

        return render(request, 'root_app/pages/reports.html', toHTML)
 
 

def mapsView(request):

    return render(request, 'root_app/pages/maps.html')

def singleMapView(request):

    return render(request, 'root_app/pages/map-details.html')

def articlesView(request):

    return render(request, 'root_app/pages/articles.html')

def articleView(request):

    return render(request, 'root_app/pages/article-details.html')

def contactView(request):

    return render(request, 'root_app/pages/contact.html')

app/root_app/templates/root_app/components/base-map.html
{% load static %}

<div class="box basemap">
    <div class="d-flex justify-content-between box-title"> 
        <h4 class="title-text"> Basemaps</h4>
        <i class="close closebox fa-solid fa-circle-xmark my-auto"></i>
    </div>
    <div class="box-body">
        <div class="row row-cols-12 gap-2 justify-content-center">

            <div class="row basemap-container" id="basemap1">
              <div class="col-4 lgndthumb">
                <img src="{% static 'root_app/assets/images/maplegend/cartodb_positron.png' %}">
              </div>
              <div class="col-8">
                <p>OpenStreet</p>
              </div>
            </div>
            
            <div class="row basemap-container" id="basemap6">
              <div class="col-4 lgndthumb" >
                  <img src="{% static 'root_app/assets/images/maplegend/esri_oceanbasemap.png' %} ">
              </div>
              <div class="col-8">
                <p>Ocean</p>
              </div>
            </div>

            <div class="row basemap-container" id="basemap3">
              <div class="col-4 lgndthumb" >
                <img src="{% static 'root_app/assets/images/maplegend/esri_worldterrain.png' %} ">
              </div>
              <div class="col-8">
                <p>Hybrid</p>
              </div>
            </div>

            <div class="row basemap-container" id="basemap2">
              <div class="col-4 lgndthumb">
                <img src="{% static 'root_app/assets/images/maplegend/here_satelliteday.png' %} ">
              </div>
              <div class="col-8">
                <p>Satellite</p>
                <!-- <p>Esri Satellite</p> -->
              </div>
            </div>
            
            <div class="row basemap-container" id="basemap5">
              <div class="col-4 lgndthumb" >
                <img src="{% static 'root_app/assets/images/maplegend/stamen_toner.png' %} ">
              </div>
              <div class="col-8">
                <p>OpenTopoMap</p>
              </div>
            </div>

            <div class="row basemap-container" id="basemap13">
              <div class="col-4 lgndthumb" >
                <img src="{% static 'root_app/assets/images/maplegend/carto_white.png' %} ">
              </div>
              <div class="col-8">
                <p>CartoDB.Positron</p>
              </div>
            </div>

            <div class="row basemap-container" id="basemap11">
              <div class="col-4 lgndthumb" >
                <img src="{% static 'root_app/assets/images/maplegend/carto.png' %} ">
              </div>
              <div class="col-8">
                <p>CartoDB.DarkMatter</p>
              </div>
            </div>

            <div class="row basemap-container" id="no_basemap">
              <div class="col-4 lgndthumb" >
                  <img src="{% static 'root_app/assets/images/maplegend/white.png' %}">
              </div> 
              <div class="col-8">
                <p>Clear</p>
              </div>
            </div>
                
             
        </div>
    </div>
</div>

app/root_app/templates/root_app/components/data-request.html
  <!-- Modal -->
  <div class="modal fade" id="dataRequestModal" tabindex="-1" aria-labelledby="dataRequestModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="dataRequestModalLabel">Data Request</h5>
          <button type="button" class="btn-close closee" data-bs-dismiss="modal" aria-label="Close">
            <i class="fa-solid fa-circle-xmark my-auto"></i>

          </button>
        </div>
        <div class="modal-body">
          <div id="data-request-loading-spinner" class="spinner d-none">
            <div class="spinner-icon"></div>
          </div>
            <form id="data_request_form" class="needs-validation" novalidate>
                <div class="row mt-2">
                  {% csrf_token %}
                    <div class="mb-4 col-6">
                      <label for="name" class="form-label">Name / Organization </label>
                        <input type="text" class="form-control" id="name" name="name" placeholder="name" required>
                        <div class="invalid-feedback">
                          Please enter your name.
                        </div>
                    </div>
                    <div class="mb-4 col-6">
                      <label for="email" class="form-label">Email</label>
                      <input type="email" class="form-control" id="email" name="email" placeholder="your.email@mail.com" required>
                      <div class="invalid-feedback">
                        Please enter your email.
                      </div>
                    </div>
                    <div class="mb-4 col-12">
                      <label for="subject" class="form-label">Subject</label>
                        <input type="text" class="form-control" id="subject" name="subject" placeholder="Data Request" required>
                        <div class="invalid-feedback">
                          Subject is required.
                        </div>
                    </div>
                    <div class="col-12">
                      <label for="comments" class="form-label">Comments</label>
                      <textarea class="form-control" name="comments" placeholder="Leave a comment here" id="floatingTextarea2" style="height: 100px"></textarea>
                    </div>
                </div>
                <div class="justify-content-between  mt-4 mb-1">
                  <button type="submit" id="data_request_submit" class="btn btn-lg w-100">Request</button>
                </div>
            </form>
        </div>
      </div>
    </div>
  </div>

app/root_app/templates/root_app/components/manual.html
<div class="box manual">
    <div class="d-flex justify-content-between box-title">
      <h4 class="title-text"> Web Manual</h4>
      <i class="close closebox fa-solid fa-circle-xmark my-auto"></i>
    </div>
    <div class="report-container" style="margin-top: 10px; padding: 5px 15px 5px 15px;">

      <div class="border manual-btn-div rounded shadow bg-body mb-3">
        <button id="manual_btn" type="button" class="btn btn-success closebox rounded w-100"><i class="fa-solid fa-book-open-reader pe-2"></i>Explore portal</a></button>
      </div>

      {% if manual %}
      <div class="report-card border shadow bg-body">
        <div class="row h-100">
          <div class="col-4">
            <img class="report-img" src="{{manual.image.url}}">
          </div>
          <div class="col-8 ps-0 pt-2">
            <p class="report-title">{{manual.name |truncatechars:45}}</p>
            <div class="row report-btns">
              <button class="col-6 btn"><a class="d-flex align-items-center" href="{{manual.document.url}}" download><i
                    class="fa-solid fa-download pe-2"></i> Download</a></button>
              <button class="col-6 btn"><a class="d-flex align-items-center" target="_blank" href="{{manual.document}}"><i
                    class="fa-solid fa-eye pe-2"></i>View </a></button>
            </div>
          </div>
        </div>
      </div>
      {% endif %}

    </div>
  </div>
  

app/root_app/templates/root_app/components/map-modal.html
{% load static %}
  <!-- Modal -->
  <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-fullscreen">
      <div class="modal-content">
        <!-- <div class="modal-header">
          <h1 class="modal-title fs-5" id="exampleModalLabel">Modal title</h1>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div> -->
        <div id="map-modal-body" class="modal-body">
            <div id="print-map-container" class="print-map-container">
                <div class="map-header">
                  <input id="map_title" class="title" for="title" placeholder="Map title here" />
                    <!-- <h1 class="title">COCOA COMMUNITIES OF SEFWI WIAWSO DISTRICT</h1> -->
                </div>
        
                <div class="map-content">
                    <div class="right-side">
                      <!-- Replace this with your map image or an embedded map -->
                        <div id="map-img-container" class="map-img-container leaflet-container leaflet-touch leaflet-fade-anim leaflet-grab leaflet-touch-drag leaflet-touch-zoom">
                  
                            <!-- <img class="map-image" src="{% static 'root_app/assets/images/map.jpg' %}" alt="map"> -->
                        </div>
                    </div>
        
                    <div class="side-content">
                        <div class="north-arrow">
                             <!-- North arrow representation -->
                             <img class="north-arrow-img" src="{% static 'root_app/assets/images/arrow.png' %}" alt="north-arrow">
                        </div>
        
                        <div class="scale">
                            <!-- Scale representation -->
                            <div class="scale-bar"></div>
                            <span class="scale-text">1 km</span>
                        </div>
        
                        <div class="legend">
                             <!-- Legend representation -->
                             <img class="legend-img" src="{% static 'root_app/assets/images/legend.png' %}" alt="legend">
                        </div>
        
                        <div class="logo">
                             <!-- Logo representation -->
                             <img class="logo-img" src="{% static 'root_app/assets/images/logo.jpg' %}" alt="logo">
                        </div>
        
                    </div>
                </div>
            </div>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
          <button type="button" class="btn btn-primary" onclick="downloadLayoutAsImage()">Print</button>
        </div>
      </div>
    </div>
  </div>

app/root_app/templates/root_app/components/map.html
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="{% static 'root_app/assets/styles/custom-map.css' %}">
</head>
<body>
    <div id="print-map-container" class="print-map-container">
        <div class="map-header">
            <input id="map_title" class="title" for="title" placeholder="Map title here" />
            <!-- <h1 class="title">COCOA COMMUNITIES OF SEFWI WIAWSO DISTRICT</h1> -->
        </div>

        <div class="map-content">
            <div class="right-side">
                <div class="map-img-container">
                    <!-- Replace this with your map image or an embedded map -->
                    <img class="map-image" src="{% static 'root_app/assets/images/map.jpg' %}" alt="map">
                </div>
            </div>

            <div class="side-content">
                <div class="north-arrow">
                     <!-- North arrow representation -->
                     <img class="north-arrow-img" src="{% static 'root_app/assets/images/arrow.jpg' %}" alt="north-arrow">
                </div>

                <div class="scale">
                    <!-- Scale representation -->
                    <div class="scale-bar"></div>
                    <span class="scale-text">1 km</span>
                </div>

                <div class="legend">
                     <!-- Legend representation -->
                     <img class="legend-img" src="{% static 'root_app/assets/images/legend.png' %}" alt="legend">
                </div>

                <div class="logo">
                     <!-- Logo representation -->
                     <img class="logo-img" src="{% static 'root_app/assets/images/logo.jpg' %}" alt="logo">
                </div>

            </div>
        </div>
    </div>
</body>


    <!-- To allow download entire webpage  -->
    <script src="https://cdn.jsdelivr.net/npm/html2canvas@1.4.1/dist/html2canvas.min.js"></script>

<script>
  // JavaScript function to download the webpage layout as an image
  function downloadLayoutAsImage() {
      const element = document.getElementById('map-container'); // The area you want to capture

      html2canvas(element, {
          useCORS: true,
          backgroundColor: '#ffffff' // Set a background color
      }).then(canvas => {
          const link = document.createElement('a');
          link.href = canvas.toDataURL('image/png');
          link.download = 'web-layout.png';
          link.click();
      });
  }
</script>
</html>

app/root_app/templates/root_app/components/reference.html
{% url 'galamseyPortal:galamsey_map_view' as galamsey_portal_url %}
{% url 'charcoalPortal:charcoal_map_view' as charcoal_portal_url %}
<div class="box reference">
  <div class="d-flex justify-content-between box-title">
    <h4 class="title-text">Additional Layers</h4>
    <i class="close closebox fa-solid fa-circle-xmark my-auto"></i>
  </div>
  <div class="box-body">
    <div class="row rows-cols-12 gap-2 justify-content-center">
      {% if request.path == galamsey_portal_url %}

      {% for additional_layer in additional_layers %}
      <div class="addition-layer" onclick="window.open('{{additional_layer.url}}', '_blank');">
          <p class="layer-name text-capitalize">{{additional_layer.name}}</p>
      </div>
      {% endfor %}

      <div class="row row-cols-12 gap-2 justify-content-center referencedata-container">
        <div class="col-12" data-bs-toggle="collapse" data-bs-target="#referenceItem" aria-expanded="false" aria-controls="referenceItem">
          <p class="layer-name text-capitalize">LU/LC</p>
        </div>
        <div id="referenceItem" class="reference-subitem-container border border-2 collapse col-11">
          <div class="form-check form-check-reverse custom-switch">
            <input type="checkbox" class="form-check-input switch-input-cluster" id="watershed_2019"
            name="watershed_2019">
            <label class="form-check-label" for="watershed_2019"></label>
          </div>
          <p class="layer-name">2019</p>
        </div>
        <div id="referenceItem" class="reference-subitem-container border border-2 collapse col-11">
          <div class="form-check form-check-reverse custom-switch">
            <input type="checkbox" class="form-check-input switch-input-cluster" id="watershed_2024"
            name="watershed_2024">
            <label class="form-check-label" for="watershed_2024"></label>
          </div>
          <p class="layer-name">2024</p>
        </div>
      </div>
      <div class="addition-layer">
        <!-- Water Shed Toggle -->
        <div class="form-check form-check-reverse custom-switch">
            <input 
                type="checkbox" 
                class="form-check-input switch-input-cluster" 
                style="float: left;" 
                id="watershed_layer" 
                name="watershed_layer">
            <label class="form-check-label" for="watershed_layer"></label>
        </div>
        <p class="layer-name text-capitalize">Watershed</p>
    </div>
    </div>

<!-- 
      {% if waford_years %}
      <div class="row row-cols-12 gap-2 justify-content-center referencedata-container">
        <div class="col-12" data-bs-toggle="collapse" data-bs-target="#referenceItem" aria-expanded="false" aria-controls="referenceItem">
          <p class="layer-name text-capitalize">Forest Degradation</p>
        </div>
        {% for waford in waford_years %}
        <div id="referenceItem" class="reference-subitem-container border border-2 collapse col-11">
          <div class="form-check form-check-reverse custom-switch">
            <input type="checkbox" class="form-check-input switch-input-cluster" id="waford_{{waford.year}}"
            name="waford_{{waford.year}}">
            <label class="form-check-label" for="waford_{{waford.year}}"></label>
          </div>
          <p class="layer-name">{{waford.year}}</p>
        </div>
        {% endfor %}
      </div>
      {% endif %} -->

      <!-- {% if planet_years %}
      <div class="row row-cols-12 gap-2 justify-content-center referencedata-container">
        <div class="col-12" data-bs-toggle="collapse" data-bs-target="#planetItem" aria-expanded="false" aria-controls="planetItem">
          <p class="layer-name text-capitalize">Planet Image</p>
        </div>
      {% for planet in planet_years %}
      <div id="planetItem" class="reference-subitem-container border border-2 collapse col-11">
        <div class="form-check form-check-reverse custom-switch">
          <input type="checkbox" class="form-check-input switch-input-cluster" id="planet_{{planet.year}}"
          name="planet_{{planet.year}}">
          <label class="form-check-label" for="planet_{{planet.year}}"></label>
        </div>
        <p class="layer-name">{{planet.year}}</p>
      </div>
      {% endfor %}
      </div>
      {% endif %} -->
      
      {% else %}
      <div class="row row-cols-12 gap-2 justify-content-center referencedata-container">
        <div class="col-12" data-bs-toggle="collapse" data-bs-target="#referenceItem" aria-expanded="false" aria-controls="referenceItem">
          <p class="layer-name text-uppercase">Fire Occurances</p>
        </div>
        <div id="referenceItem" class="reference-subitem-container border border-2 collapse col-11">
          <div class="form-check form-check-reverse custom-switch">
            <input type="checkbox" class="form-check-input switch-input-cluster" id="firehotspot_2020"
            name="firehotspot_2020">
            <label class="form-check-label" for="firehotspot_2020"></label>
          </div>
          <p class="layer-name">2020</p>
        </div>
      </div>
      
      <div class="addition-layer">
        <!-- LU/LC Toggle -->
        <div class="form-check form-check-reverse custom-switch">
            <input 
                type="checkbox" 
                class="form-check-input switch-input-cluster" 
                style="float: left;" 
                id="lulc_savannah" 
                name="lulc_savannah">
            <label class="form-check-label" for="lulc_savannah"></label>
        </div>
        <p class="layer-name text-capitalize">LU/LC</p>
    </div>
    
    <div class="addition-layer">
        <!-- Water Shed Toggle -->
        <div class="form-check form-check-reverse custom-switch">
            <input 
                type="checkbox" 
                class="form-check-input switch-input-cluster" 
                style="float: left;" 
                id="watershed_layer" 
                name="watershed_layer">
            <label class="form-check-label" for="watershed_layer"></label>
        </div>
        <p class="layer-name text-capitalize">WaterShed</p>
    </div>
    

      
      {% endif %}
      
    </div>
  </div>
</div>

app/root_app/templates/root_app/components/report.html
{% url 'galamseyPortal:galamsey_map_view' as galamsey_portal_url %}
<div class="box report">
    <div class="d-flex justify-content-between box-title">
      {% if request.path == galamsey_portal_url %}
      <h4 class="title-text">Reports & Maps</h4>
      {% else %}
      <h4 class="title-text">Reports </h4>
      {% endif %}
      <i class="close closebox fa-solid fa-circle-xmark my-auto"></i>
    </div>
    <div class="report-container" style="margin-top: 10px; padding: 5px 10px 5px 10px;">
      {% for report in reports %}
      <div class="report-card border shadow bg-body">
        <div class="row h-100">
          <div class="col-4" style="height: inherit;">
            {% if report.image %}
              <img class="report-img" src="{{report.image.url}}">
            {% else %}
              <img class="report-img" src="/static/assets/landing/images/thumbnail.jpg" alt="{{ report.name }}"/>
            {% endif %}
          </div>
          <div class="col-8 ps-0 pt-2">
            <p class="report-title" data-toggle="tooltip" data-placement="right" title="{{report.name}}">{{report.name |truncatechars:32}}</p>
            <div class="row report-btns">
              <button class="col-6 btn"><a class="d-flex align-items-center" href="{{report.document.url}}" download><i
                    class="fa-solid fa-download pe-2"></i> Download</a></button>
              <button class="col-6 btn"><a class="d-flex align-items-center" target="_blank" href="{{report.document.url}}"><i
                    class="fa-solid fa-eye pe-2"></i>View </a></button>
            </div>
          </div>
        </div>
      </div>
      {% endfor %}
    </div>
  </div>
  